baseURL: https://manish-003.github.io/profile-site/
languageCode: en-us
title: Manish
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "My profile"
  staticPath: https://manish-003.github.io/profile-site/
  favicon: "avatar.svg"
  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Manish"
    subtitle: "I enjoy xploring"
    content: "a curious and quick learner. presently a student persuing B.Tech Robotics and Automation"
    image: avatar.svg
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true 
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/manish-003
        - icon: fab fa-instagram
          url: https://instagram.com/instala_illa
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/manish-s-n-31b042213
        - icon: fab fa-telegram
          url: https://telegram.org/Fan_of_Myself
  
  #about
  about:
    enable: true
    title: "About me"
    image: "avatar.svg"
    content: |-
      the best way to know about me it to meet me in person.. 
      I wont ask you to judge me based on some text you saw on the internet. and i am sure meeting me will be surprise for you😉
      .
      .


    skills:
      enable: true
      title: Here are some things i have experimented with
      items:
        - "git(cli)"
        - "Python"
        - "linux"
        - "web developement"
        - "Octave"
        - "command line"
        - "shell scripting"
        - "ROS"
        - "Embedded C"
        - "markdown"
        - "ssh"
  
  education:
    enable: true
    items:
      - title: "Bachelor of Technogy"
        school:
          name: "Rajalakshmi Engineering College"
          url: "https://www.rajalakshmi.org/"
        date: "2020 - 2024"
      - title: "Higher Sceondary Education"
        school:
          name: "Vairams matric Higher Sceondary School"
        date: "2020"
        GPA: "502/600"
      - title: "high education(SSLC)"
        school:
          name: "Vairams matric Higher Sceondary School"
        date: "2018"
        GPA: "475/500"

  contact:
    enable: true
    content:  My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    email: manish2k03@pm.me
    btnName: Mail me!

  footer:
    socialNetworks:
        github: https://github.com/manish-003
        linkedin: https://linkedin.com/in/manish-s-n-31b042213
        instagram: https://instagram.com/instala_illa
